#!/bin/sh

# Enable Dropbear SSH server
uci set dropbear.@dropbear[0].enable='1'
uci set dropbear.@dropbear[0].Port='22'
uci set dropbear.@dropbear[0].PasswordAuth='on'
uci set dropbear.@dropbear[0].RootPasswordAuth='on'
uci commit dropbear

# Set root password to 'root'
echo -e "root\nroot" | passwd root

# Enable and start dropbear
/etc/init.d/dropbear enable
/etc/init.d/dropbear start

