#!/bin/sh /etc/rc.common
START=99

start() {
    uci set dropbear.@dropbear[0].enable='1'
    uci set dropbear.@dropbear[0].Port='22'
    uci set dropbear.@dropbear[0].PasswordAuth='on'
    uci set dropbear.@dropbear[0].RootPasswordAuth='on'
    uci commit dropbear
    /etc/init.d/dropbear enable
    /etc/init.d/dropbear start
    echo -e "root\nroot" | passwd root
}


