name: Build GL-MT3000 ImmortalWrt

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up job
      run: mkdir imagebuilder

    - name: Download ImageBuilder
      run: |
        curl -L -o imagebuilder.tar.xz https://downloads.immortalwrt.org/snapshots/targets/mediatek/filogic/immortalwrt-imagebuilder-mediatek-filogic.Linux-x86_64.tar.xz
        tar -xJf imagebuilder.tar.xz -C imagebuilder --strip-components=1

    - name: Run Build
      run: |
        cd imagebuilder
        make image PROFILE="gl-mt3000" PACKAGES="luci luci-ssl iperf3 ipset curl bash kmod-usb-net kmod-mt7921e" FILES=files/

    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: imagebuilder/bin/targets/








