name: Build GL-MT3000 ImmortalWrt

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y curl unzip zstd

      - name: Download ImageBuilder
        run: |
          mkdir imagebuilder
          curl -Lo - https://downloads.immortalwrt.org/releases/23.05.3/targets/mediatek/filogic/immortalwrt-imagebuilder-23.05.3-mediatek-filogic.Linux-x86_64.tar.zst \
          | zstd -d | tar -xvf - -C imagebuilder --strip-components=1

      - name: Copy files into ImageBuilder
        run: |
          cp -rf files imagebuilder/files

      - name: Run Build Script
        run: |
          cd imagebuilder
          make image PROFILE=glinet_gl-mt3000 \
            ENABLE_IPV6=y \
            ENABLE_WIFI=y \
            PACKAGES="luci luci-ssl luci-app-openclash luci-app-homeproxy ip-full ipset iptables iptables-mod-tproxy \
            iptables-mod-extra iptables-mod-socket iptables-mod-ipopt kmod-inet-diag kmod-tun kmod-macvlan \
            kmod-nf-nathelper kmod-nf-nathelper-extra kmod-nft-socket kmod-sched-core luci-app-firewall \
            luci-app-ttyd luci-app-sqm luci-theme-argon openssh-sftp-server" \
            FILES=files/
