name: Build GL-MT3000 ImmortalWrt

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y curl tar xz-utils python3-pip python3-setuptools

    - name: Download ImageBuilder
      run: |
        mkdir imagebuilder
        cd imagebuilder
        curl -LO https://downloads.immortalwrt.org/releases/23.05.0/targets/mediatek/filogic/immortalwrt-imagebuilder-23.05.0-mediatek-filogic.Linux-x86_64.tar.xz
        tar -xvf immortalwrt-imagebuilder-23.05.0-mediatek-filogic.Linux-x86_64.tar.xz
        mv immortalwrt-imagebuilder-23.05.0-mediatek-filogic.Linux-x86_64 builder

    - name: Run Build
      run: |
        cd imagebuilder/builder
        make image PROFILE=gl-mt3000 PACKAGES="luci luci-ssl ip-full iperf3 curl bash coreutils screen htop nano openssh-sftp-server ca-certificates kmod-tun kmod-usb-net kmod-usb-net-cdc-ether kmod-mt7921e"

    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: GL-MT3000-Firmware
        path: imagebuilder/builder/bin/targets/mediatek/filogic/*.bin










