name: Build GL-MT3000 ImmortalWrt

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Set up job
        run: echo "Starting build..."

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk \
            gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
            rsync unzip zlib1g-dev file wget python3 python3-pip python3-setuptools \
            p7zip-full zstd

      - name: Download ImageBuilder
        run: |
          mkdir imagebuilder
          cd imagebuilder
          curl -LO https://downloads.immortalwrt.org/releases/23.05.4/targets/mediatek/filogic/immortalwrt-imagebuilder-23.05.4-mediatek-filogic.Linux-x86_64.tar.xz
          tar -xJf immortalwrt-imagebuilder-23.05.4-mediatek-filogic.Linux-x86_64.tar.xz
          mv immortalwrt-imagebuilder-23.05.4-mediatek-filogic.* builder

      - name: Copy files into ImageBuilder
        run: |
          echo "No custom files to copy"

      - name: Run Build Script
        run: |
          cd imagebuilder/builder
          make image PROFILE=gl-mt3000 \
            PACKAGES="luci luci-ssl luci-app-openclash curl wget iperf3 ip-full ipset iptables" \
            FILES=files

      - name: Post Checkout
        run: echo "Build completed"

      - name: Complete job
        run: echo "Done!"



