name: Build GL-MT3000 ImmortalWrt

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Build Script
        run: |
          sudo apt update
          sudo apt install -y curl
          chmod +x ./mediatek-filogic/build.sh
          ./mediatek-filogic/build.sh glinet_gl-mt3000
