name: Build GL-MT3000 ImmortalWrt

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up job
        run: echo "Starting build process"

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip python3-venv wget curl
          wget http://archive.ubuntu.com/ubuntu/pool/universe/p/python3-stdlib-extensions/python3-distutils_3.12.2-1_all.deb
          sudo dpkg -i python3-distutils_3.12.2-1_all.deb

      - name: Download ImageBuilder
        run: |
          wget https://downloads.immortalwrt.org/releases/23.05.0/targets/mediatek/filogic/immortalwrt-imagebuilder-23.05.0-mediatek-filogic.Linux-x86_64.tar.xz
          tar -Jxf immortalwrt-imagebuilder-23.05.0-mediatek-filogic.Linux-x86_64.tar.xz
          mv immortalwrt-imagebuilder-23.05.0-mediatek-filogic imagebuilder

      - name: Copy files into ImageBuilder
        run: |
          cp -r files imagebuilder/files

      - name: Run Build
        run: |
          cd imagebuilder
          make image PROFILE=gl-mt3000 FILES=files/ PACKAGES="luci luci-ssl ip-full ipset iptables iptables-mod-tproxy iptables-mod-extra kmod-inet-diag kmod-sched-core kmod-tun kmod-mt7921e kmod-mt7921-common kmod-mt76-connac kmod-mt76-core kmod-mt76 kmod-mt76x2u kmod-mt7615e kmod-mt7615-common"

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: GL-MT3000-Firmware
          path: imagebuilder/bin/targets/mediatek/filogic/*.bin






























