port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
allow-lan: true
bind-address: "*"
mode: rule
log-level: info
ipv6: false

dns:
  enable: true
  listen: 0.0.0.0:7874
  enhanced-mode: fake-ip
  default-nameserver: [1.1.1.1, 8.8.8.8]
  nameserver: [https://1.1.1.1/dns-query]
  fallback: [https://8.8.8.8/dns-query]

proxies:
  - name: "MyVLESS"
    type: vless
    server: 144.202.113.155
    port: 443
    uuid: 378e1350-afa5-4042-afc9-d9d92667906a
    tls: true
    network: tcp
    client-fingerprint: chrome

proxy-groups:
  - name: "AUTO"
    type: select
    proxies:
      - MyVLESS
      - DIRECT

rules:
  - DOMAIN-KEYWORD,tiktok,AUTO
  - DOMAIN-SUFFIX,youtube.com,AUTO
  - DOMAIN-SUFFIX,google.com,AUTO
  - GEOIP,CN,DIRECT
  - MATCH,AUTO









































