name: Build GL-MT3000 ImmortalWrt

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libncurses5-dev \
            zlib1g-dev \
            gawk \
            git \
            wget \
            unzip \
            python3 \
            python3-pip

      - name: Download ImageBuilder
        run: |
          wget https://downloads.immortalwrt.org/releases/23.05.0/targets/mediatek/filogic/immortalwrt-imagebuilder-23.05.0-mediatek-filogic.Linux-x86_64.tar.xz
          tar -xvf immortalwrt-imagebuilder-23.05.0-mediatek-filogic.Linux-x86_64.tar.xz
          mv immortalwrt-imagebuilder-23.05.0-mediatek-filogic.Linux-x86_64 imagebuilder

      - name: Copy files into ImageBuilder
        run: |
          mkdir -p imagebuilder/files
          cp -r ./files/* imagebuilder/files/ || true

      - name: Run Build
        run: |
          cd imagebuilder
          make image PROFILE=glinet_gl-mt3000 PACKAGES="curl bash dropbear uci-defaults" FILES=files

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: GL-MT3000-firmware
          path: imagebuilder/bin/targets/**/**/*.bin











































