name: Build GL-MT3000 ImmortalWrt

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up job
        run: echo "Starting build for GL-MT3000..."

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev \
            zlib1g-dev gawk git ccache gettext libssl-dev xsltproc \
            rsync wget unzip python3-distutils

      - name: Download ImageBuilder
        run: |
          mkdir imagebuilder
          cd imagebuilder
          wget https://downloads.immortalwrt.org/snapshots/targets/mediatek/filogic/immortalwrt-imagebuilder-mediatek-filogic.Linux-x86_64.tar.xz
          tar -xvf immortalwrt-imagebuilder-mediatek-filogic.Linux-x86_64.tar.xz --strip=1

      - name: Copy files into ImageBuilder
        run: |
          mkdir -p imagebuilder/files/etc
          # Add any custom files you want into imagebuilder/files/ if needed
          echo "files copied"

      - name: Run Build
        run: |
          cd imagebuilder
          make image PROFILE="glinet_gl-mt3000" PACKAGES="luci kmod-mt7915e kmod-usb3 kmod-usb-net kmod-usb-net-cdc-ether iperf3 ipset kmod-ipt-geoip kmod-ipt-nat kmod-nft-core kmod-nft-nat kmod-tun kmod-wireguard luci-app-openclash"

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: imagebuilder/bin/targets/*/*


















