name: Build GL-MT3000 ImmortalWrt

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Build Script
        run: |
          sudo apt update
          sudo apt install -y curl
          chmod +x ./mediatek-filogic/build.sh
          PROFILE=glinet_gl-mt3000 \
          ENABLE_PPPOE=false \
          PPPOE_ACCOUNT=none \
          PPPOE_PASSWORD=none \
          INCLUDE_DOCKER=yes \
          ./mediatek-filogic/build.sh
