name: Build GL-MT3000 ImmortalWrt

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up job
        run: echo "Starting job..."

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libncurses5-dev libncursesw5-dev zlib1g-dev \
            gawk git gettext libssl-dev xsltproc wget unzip python3 python3-pip python3-setuptools \
            python3-wheel python3-venv python3-dev python3-apt libelf-dev ecj fastjar curl \
            python3.10-distutils || sudo apt install -y python3.11-distutils

      - name: Download ImageBuilder
        run: |
          wget https://downloads.openwrt.org/releases/23.05.3/targets/mediatek/filogic/openwrt-imagebuilder-23.05.3-mediatek-filogic.Linux-x86_64.tar.xz
          tar -xf openwrt-imagebuilder-23.05.3-mediatek-filogic.Linux-x86_64.tar.xz
          mv openwrt-imagebuilder-23.05.3-mediatek-filogic.Linux-x86_64 imagebuilder

      - name: Copy files into ImageBuilder
        run: |
          mkdir -p imagebuilder/files/etc
          # Copy any custom files if needed

      - name: Run Build
        run: |
          cd imagebuilder
          make image PROFILE=gl-mt3000 PACKAGES="luci luci-ssl iperf3 curl wget bash"

      - name: Upload firmware
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: imagebuilder/bin/targets/**/openwrt-*.bin























