name: Build GL-MT3000 ImmortalWrt

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up job
        run: echo "Setting up build job..."

      - name: Set up environment
        run: |
          sudo apt update
          sudo apt install -y build-essential libncurses5-dev gawk git \
            subversion libssl-dev gettext unzip file python3 python3-pip wget curl

      - name: Download ImageBuilder
        run: |
          wget https://downloads.immortalwrt.org/releases/23.05.0/targets/mediatek/filogic/immortalwrt-imagebuilder-23.05.0-mediatek-filogic.Linux-x86_64.tar.xz
          tar -Jxf immortalwrt-imagebuilder-23.05.0-mediatek-filogic.Linux-x86_64.tar.xz
          mv immortalwrt-imagebuilder-23.05.0-mediatek-filogic imagebuilder

      - name: Copy files into ImageBuilder
        run: |
          mkdir -p imagebuilder/files/etc
          # Optionally add your own files like configs here

      - name: Run Build
        run: |
          cd imagebuilder
          make image PROFILE="glinet_gl-mt3000" PACKAGES="luci luci-ssl dnsmasq-full iptables ip6tables \
          kmod-tun curl ca-certificates bash coreutils libustream-openssl -libustream-mbedtls"

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: gl-mt3000-firmware
          path: imagebuilder/bin/targets/mediatek/filogic/*.bin





























