name: Build GL-MT3000 ImmortalWrt

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip python3-setuptools python3-distutils unzip curl

      - name: Download ImageBuilder
        run: |
          curl -L -o imagebuilder.tar.xz https://downloads.immortalwrt.org/releases/23.05.0/targets/mediatek/filogic/immortalwrt-imagebuilder-23.05.0-mediatek-filogic.Linux-x86_64.tar.xz
          mkdir -p imagebuilder
          tar -xJf imagebuilder.tar.xz -C imagebuilder --strip-components=1

      - name: Copy files into ImageBuilder
        run: |
          cp -r files imagebuilder/files || true
          cp -r custom-packages imagebuilder/custom-packages || true

      - name: Run Build
        run: |
          cd imagebuilder
          make image PROFILE=gl-mt3000 PACKAGES="luci luci-ssl luci-app-upnp luci-app-ddns iperf3 curl" FILES=files

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: GL-MT3000-Firmware
          path: imagebuilder/bin/targets/*/*/immortalwrt-*.bin































