name: Build GL‑MT3000 ImmortalWrt

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y curl xz-utils make gcc g++ pkg-config

    - name: Download ImageBuilder
      run: |
        mkdir -p imagebuilder
        cd imagebuilder
        curl -L -o ib.tar.xz https://downloads.immortalwrt.org/releases/23.05-SNAPSHOT/targets/mediatek/filogic/immortalwrt-imagebuilder-23.05-SNAPSHOT-mediatek-filogic.Linux-x86_64.tar.xz
        tar -xJf ib.tar.xz
        mv immortalwrt-imagebuilder-* builder

    - name: Prepare files
      run: |
        mkdir -p imagebuilder/builder/files
        # Add any custom config files into imagebuilder/builder/files if needed

    - name: Run Build
      run: |
        cd imagebuilder/builder
        make info
        make image PROFILE=gl-mt3000 PACKAGES="luci" FILES=files

    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: imagebuilder/builder/bin/targets/mediatek/filogic/*.bin












