name: Build GL-MT3000 ImmortalWrt

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up job
        run: echo "Starting build..."

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip python3-venv \
            build-essential libncurses5-dev zlib1g-dev gawk git ccache \
            gettext libssl-dev xsltproc rsync wget unzip

      - name: Download ImageBuilder
        run: |
          mkdir -p imagebuilder
          cd imagebuilder
          wget https://downloads.openwrt.org/releases/23.05.3/targets/mediatek/filogic/openwrt-imagebuilder-23.05.3-mediatek-filogic.Linux-x86_64.tar.xz
          tar -xf openwrt-imagebuilder-23.05.3-mediatek-filogic.Linux-x86_64.tar.xz
          mv openwrt-imagebuilder-23.05.3-mediatek-filogic.Linux-x86_64 builder

      - name: Copy files into ImageBuilder
        run: |
          mkdir -p imagebuilder/builder/files/etc
          echo "set up files here if needed"

      - name: Run Build
        run: |
          cd imagebuilder/builder
          make image PROFILE=glinet_gl-mt3000 \
            PACKAGES="luci luci-ssl luci-app-upnp luci-app-ddns \
            iptables ip6tables kmod-usb-storage \
            kmod-mt7915e kmod-mt7981-firmware \
            dnsmasq-full ca-certificates curl iperf3"
          
      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-gl-mt3000
          path: imagebuilder/builder/bin/targets/*/*/*.bin



















