name: Build GL-MT3000 ImmortalWrt

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib \
            gettext git libncurses-dev libssl-dev python3-distutils python3-pip rsync unzip \
            zlib1g-dev file wget libelf-dev ecj fastjar java-propose-classpath \
            python3-setuptools python3-wheel

      - name: Download ImageBuilder
        run: |
          wget https://downloads.openwrt.org/releases/23.05.3/targets/mediatek/filogic/openwrt-imagebuilder-23.05.3-mediatek-filogic.Linux-x86_64.tar.xz
          tar -Jxf openwrt-imagebuilder-23.05.3-mediatek-filogic.Linux-x86_64.tar.xz
          mv openwrt-imagebuilder-23.05.3-mediatek-filogic.Linux-x86_64 imagebuilder

      - name: Copy files into ImageBuilder
        run: |
          cp -r files imagebuilder/files || true
          cp -r custom-packages/* imagebuilder/ || true

      - name: Run Build
        run: |
          cd imagebuilder
          make image PROFILE="gl-mt3000" PACKAGES="-ppp -pppoe -odhcpd-ipv6only -dnsmasq +luci +luci-ssl +ipset +ip-full +iptables +kmod-mt7915e +kmod-mt7981-firmware +kmod-mt7986-firmware +kmod-nft-fullcone" FILES=files/

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: gl-mt3000-firmware
          path: imagebuilder/bin/targets/mediatek/filogic/*.bin





































