name: Build GL-MT3000 ImmortalWrt

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up job
        run: echo "Starting firmware build..."

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
            gettext git libncurses-dev libssl-dev python3-distutils rsync unzip zlib1g-dev \
            file wget python3 python3-pip python3-setuptools

      - name: Download ImageBuilder
        run: |
          mkdir -p imagebuilder
          curl -L -o imagebuilder.tar.xz https://downloads.immortalwrt.org/snapshots/targets/mediatek/filogic/immortalwrt-imagebuilder-mediatek-filogic.Linux-x86_64.tar.xz
          tar -xvf imagebuilder.tar.xz -C imagebuilder --strip-components=1

      - name: Copy files into ImageBuilder
        run: |
          mkdir -p imagebuilder/files/etc/config
          echo 'config system\n  option hostname '\''ImmortalWrt'\''' > imagebuilder/files/etc/config/system

      - name: Run Build
        run: |
          cd imagebuilder
          make image PROFILE=gl-mt3000 PACKAGES="luci luci-ssl iperf3 iptables ipset kmod-mt7915e kmod-mt7981-firmware" FILES=files

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: GL-MT3000-Firmware
          path: imagebuilder/bin/targets/**/*.bin
















