name: Build GL-MT3000 ImmortalWrt

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up job
        run: echo "Job started"

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex bison g++ gawk \
            gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
            python3-distutils rsync unzip zlib1g-dev file wget python3

      - name: Download ImageBuilder
        run: |
          wget https://downloads.immortalwrt.org/releases/23.05.0/targets/mediatek/filogic/immortalwrt-imagebuilder-23.05.0-mediatek-filogic.Linux-x86_64.tar.xz
          tar -Jxf immortalwrt-imagebuilder-23.05.0-mediatek-filogic.Linux-x86_64.tar.xz
          DIR=$(tar -tf immortalwrt-imagebuilder-23.05.0-mediatek-filogic.Linux-x86_64.tar.xz | head -1 | cut -f1 -d"/")
          mv "$DIR" imagebuilder

      - name: Copy files into ImageBuilder
        run: |
          mkdir -p imagebuilder/files/etc/config
          echo "custom config here" > imagebuilder/files/etc/config/custom.conf

      - name: Run Build
        run: |
          cd imagebuilder
          make image PROFILE="gl-mt3000" PACKAGES="luci luci-ssl curl ip-full"
      
      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: gl-mt3000-firmware
          path: imagebuilder/bin/targets/*/*/*.bin





























