name: Build GL-MT3000 ImmortalWrt

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev libncursesw5-dev zlib1g-dev gawk git ccache gettext libssl-dev xsltproc rsync wget unzip python3 python3-pip python3-setuptools python3-distutils

    - name: Download ImageBuilder
      run: |
        wget https://downloads.immortalwrt.org/releases/23.05.0/targets/mediatek/filogic/immortalwrt-imagebuilder-23.05.0-mediatek-filogic.Linux-x86_64.tar.xz
        tar -Jxf immortalwrt-imagebuilder-23.05.0-mediatek-filogic.Linux-x86_64.tar.xz
        mv immortalwrt-imagebuilder-23.05.0-mediatek-filogic imagebuilder

    - name: Copy files into ImageBuilder
      run: |
        cp -r files imagebuilder/files || true

    - name: Run Build
      run: |
        cd imagebuilder
        make image PROFILE=glinet_gl-mt3000 PACKAGES="luci luci-ssl clash ip-full bash curl wget ipset dnsmasq-full coreutils tar gzip p7zip unzip" FILES=files

    - name: Upload firmware
      uses: actions/upload-artifact@v3
      with:
        name: firmware
        path: imagebuilder/bin/targets/*/*/*.bin


































