name: Build GL-MT3000 ImmortalWrt

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y curl

      - name: Make build script executable
        run: |
          chmod +x ./mediatek-filogic/build.sh

      - name: Run Build Script
        run: |
          PROFILE=glinet_gl-mt3000 \
          ENABLE_PPPOE=false \
          PPPOE_ACCOUNT=none \
          PPPOE_PASSWORD=none \
          ./mediatek-filogic/build.sh

