name: Build GL-MT3000 ImmortalWrt

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib \
            gettext git libncurses-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget

      - name: Download ImageBuilder
        run: |
          wget https://downloads.immortalwrt.org/releases/23.05.0/targets/mediatek/filogic/immortalwrt-imagebuilder-23.05.0-mediatek-filogic.Linux-x86_64.tar.xz
          tar -xJf immortalwrt-imagebuilder-23.05.0-mediatek-filogic.Linux-x86_64.tar.xz
          extracted_dir=$(tar -tf immortalwrt-imagebuilder-23.05.0-mediatek-filogic.Linux-x86_64.tar.xz | head -1 | cut -f1 -d"/")
          mv "$extracted_dir" imagebuilder

      - name: Copy files into ImageBuilder
        run: |
          mkdir -p imagebuilder/files/etc/config
          cp -r files/* imagebuilder/files/ || true

      - name: Run Build
        run: |
          cd imagebuilder
          make image PROFILE=gl-mt3000 PACKAGES="luci luci-app-ttyd luci-app-upnp ip-full ipset iptables-mod-tproxy iptables-mod-extra iptables-nft iptables-mod-tproxy kmod-inet-diag kmod-tun kmod-sched-core kmod-sched-cake kmod-nft-tproxy kmod-nft-socket kmod-nft-compat luci-app-firewall luci-app-openclash bash"

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: GL-MT3000-ImmortalWrt
          path: imagebuilder/bin/targets/mediatek/filogic/*.bin


























