name: Build GL‑MT3000 ImmortalWrt

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y curl xz-utils unzip

      - name: Download ImageBuilder
        run: |
          curl -L -o imagebuilder.tar.xz https://downloads.immortalwrt.org/releases/24.10.0/targets/mediatek/filogic/immortalwrt-imagebuilder-24.10.0-mediatek-filogic.Linux‑x86_64.tar.zst
          mkdir imagebuilder
          tar -x --zstd -f imagebuilder.tar.xz -C imagebuilder --strip-components=1

      - name: Copy files into ImageBuilder
        run: |
          mkdir -p imagebuilder/files
          cp -r files/* imagebuilder/files/

      - name: Run Build Script
        run: |
          chmod +x mediatek-filogic/build.sh
          cd imagebuilder
          PROFILE=glinet_gl-mt3000 \
          ENABLE_PPPOE=false \
          PPPOE_ACCOUNT=none \
          PPPOE_PASSWORD=none \
          INCLUDE_DOCKER=yes \
          ../mediatek-filogic/build.sh


