name: Build GL-MT3000 ImmortalWrt

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y curl unzip tar zstd

    - name: Download ImageBuilder
      run: |
        mkdir imagebuilder
        curl -L https://downloads.immortalwrt.org/releases/23.05.3/targets/mediatek/filogic/immortalwrt-imagebuilder-23.05.3-mediatek-filogic.Linux-x86_64.tar.zst | zstd -d | tar -xvf - -C imagebuilder --strip-components=1

    - name: Copy files into ImageBuilder
      run: |
        cp -r files/ imagebuilder/files

    - name: Run Build Script
      run: |
        cd imagebuilder
        make image PROFILE=glinet_gl-mt3000 ENABLE_IPV6=y ENABLE_WIFI=y

