name: Build GL‑MT3000 ImmortalWrt

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y curl xz-utils make gcc g++ pkg-config

    - name: Download ImageBuilder
      run: |
        mkdir imagebuilder
        cd imagebuilder
        curl -L -o ib.tar.xz https://downloads.immortalwrt.org/releases/23.05-SNAPSHOT/targets/mediatek/filogic/immortalwrt-23.05-snapshot-*-mediatek-filogic-imagebuilder-*.tar.xz
        tar xJf ib.tar.xz

    - name: Copy pre‑config files
      run: |
        mkdir -p imagebuilder/builder/files
        # Add any files into builder/files/ if needed

    - name: Run Build
      run: |
        cd imagebuilder/builder
        make image PROFILE=gl-mt3000 \
          PACKAGES="luci openssl kmod-usb-core" \
          FILES=files

    - name: Upload firmware
      uses: actions/upload-artifact@v3
      with:
        name: gl-mt3000-firmware
        path: imagebuilder/builder/bin/targets/mediatek/filogic/*.bin











