name: Build GL-MT3000 ImmortalWrt

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up job
      run: echo "Starting build..."

    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev zlib1g-dev gawk git ccache gettext libssl-dev xsltproc unzip python3-pip python3-setuptools python3-distutils

    - name: Download ImageBuilder
      run: |
        wget https://downloads.immortalwrt.org/releases/23.05.0/targets/mediatek/filogic/immortalwrt-imagebuilder-23.05.0-mediatek-filogic.Linux-x86_64.tar.xz
        tar -xJf immortalwrt-imagebuilder-23.05.0-mediatek-filogic.Linux-x86_64.tar.xz
        mv immortalwrt-imagebuilder-23.05.0-mediatek-filogic imagebuilder

    - name: Copy files into ImageBuilder
      run: |
        cp -r files imagebuilder/files || true

    - name: Run Build
      run: |
        cd imagebuilder
        make image PROFILE=glinet_gl-mt3000 PACKAGES="luci luci-ssl ip-full ipset iptables ip6tables kmod-mt7981e kmod-mt7981-firmware" FILES=files/

    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: imagebuilder/bin/targets/*/*/immortalwrt-*.bin

































