name: Build GL-MT3000 ImmortalWrt

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y curl unzip tar zstd

      - name: Download ImageBuilder
        run: |
          mkdir imagebuilder
          curl -L -o ib.tar.zst https://downloads.immortalwrt.org/releases/23.05.3/targets/mediatek/filogic/immortalwrt-imagebuilder-23.05.3-mediatek-filogic.Linux-x86_64.tar.zst
          tar -I zstd -xf ib.tar.zst -C imagebuilder --strip-components=1

      - name: Copy files into ImageBuilder
        run: |
          cp -r files/ imagebuilder/files

      - name: Run Build Script
        run: |
          cd ./imagebuilder
          PROFILE=glinet_gl-mt3000 ENABLE_PPPOE=false PPPOE_ACCOUNT=none PPPOE_PASSWORD=none INCLUDE_DOCKER=yes ../mediatek-filogic/build.sh


